use androidx instead of support library
The support library has been replaced by androidx.
https://developer.android.com/jetpack/androidx/migrate

I know turning on `android.useAndroidX` and `android.enableJetifier` should automatically convert third party librarys to use android x,
but for this repo it wasn't the case.

It gaves the error:
```
/node_modules/react-native-image-tools-wm/android/src/main/java/net/wowmaking/Utility.java:9: error: package android.support.media does not exist
import android.support.media.ExifInterface;
                                                   ^
```

Given that whole android ecosystem & community has already adopted to use androidx, it's time to use android x flag correctly in all libraries as well.
So I'm pulling this code change.